---
title: "My Test Image For Binder"
author:
  - Rob Schick
  - Rob's Alter Ego, Dr. Bob
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    bookdown::html_document2:
      fig_caption: yes
      reference_docx: "../templates/template.docx" # Insert path for the DOCX file
bibliography: references.bib
csl: "../templates/journal-of-archaeological-science.csl" # Insert path for the bib-style
abstract: |
  I do declare this is fine work.
keywords: |
  Amazing Work; Stupendous; Captivating
highlights: |
  This is the most reproducible article ever. 
---


<!-- This is the format for text comments that will be ignored during renderings. Do not put R code in these comments because it will not be ignored. -->

```{r, setup, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = "../figures/"
)

library(firstcomp) # Or use devtools::load_all('.', quiet = T) if your code is in script files, rather than as functions in the `/R` diretory
```

# Introduction

```{r}
hist(rnorm(30), breaks = 30)
```



# Background

```{r demo}
1 + 1
```

# Methods

# Results

```{r get-data}
# Note the path that we need to use to access our data files when rendering this document
priors <- readr::read_csv(here::here('analysis', 'data', 'raw_data', 'PhilipsMay2015revisedPriorWeightsLongFormat.csv'))
head(priors)
```

Ok, once we have those, then we need to save them into a derived data file

```{r}
readr::write_rds(priors, here::here('analysis', 'data', 'derived_data', 'priors.rds'))
```


# Discussion

# Conclusion

# Acknowledgements

<!-- The following line inserts a page break when the output is MS Word. For page breaks in PDF, use \newpage on its own line.  -->
##### pagebreak

# References 
<!-- The following line ensures the references appear here for the MS Word or HTML output files, rather than right at the end of the document (this will not work for PDF files):  -->
<div id="refs"></div>

##### pagebreak

### Colophon

This report was generated on `r Sys.time()` using the following computational environment and dependencies: 

```{r colophon, cache = FALSE}
# which R packages and versions?
devtools::session_info()
```

The current Git commit details are:

```{r}
# what commit is this file at? 
git2r::repository(here::here())
```
